language: go
stages:
  - test
  - build
  - deploy
jobs:
  include:
    - go: 1.x
      os: linux
      stage: test
    - go: tip
      os: linux
      stage: test
    - go: 1.8.x
      os: linux
      stage: test
    - go: 1.9.x
      os: linux
      stage: test
    - go: 1.10.x
      os: linux
      stage: test
    - go: 1.11.x
      os: linux
      stage: test
    - go: 1.12.x
      os: linux
      stage: test
    - go: 1.13.x
      os: linux
      stage: test

    - go: 1.x
      env: LATEST=true
      os: osx
      stage: build
      script:
        - CGO_ENABLED=1 gox -os="darwin" -arch="amd64" -output="~/$TRAVIS_BUILD_NUMBER/sounddrop.{{.OS}}.{{.Arch}}" -ldflags "-X main.rev=`git rev-parse --short HEAD`" -verbose ./...
    - go: 1.x
      env: LATEST=true
      os: linux
      stage: build
      script:
        - CGO_ENABLED=1 gox -os="linux windows" -arch="amd64" -output="~/$TRAVIS_BUILD_NUMBER/sounddrop.{{.OS}}.{{.Arch}}" -ldflags "-X main.rev=`git rev-parse --short HEAD`" -verbose ./...

    - stage: deploy
      deploy:
        provider: releases
        edge: true
        draft: true
        token: $GITHUB_TOKEN
        file:
          - sounddrop.windows.amd64.exe
          - sounddrop.linux.amd64
          - sounddrop.darwin.amd64
        on:
          repo: tuarrep/sounddrop
          tags: true
  allow_failures:
    - go: tip

before_install:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli
  - mkdir -p ~/$TRAVIS_BUILD_NUMBER
  - aws s3 sync s3://$AWS_BUCKET/$TRAVIS_BUILD_NUMBER ~/$TRAVIS_BUILD_NUMBER -quiet
  - go get github.com/mitchellh/gox
  - go get github.com/konsorten/go-windows-terminal-sequences # For windows build
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt update && sudo apt install -y libasound2-dev ; fi
  - go get -t -v ./...

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet $(go list ./... | grep -v /vendor/)
  - go test -v -race ./...

after_success:
  - aws s3 sync ~/$TRAVIS_BUILD_NUMBER s3://$AWS_BUCKET/$TRAVIS_BUILD_NUMBER